version: '2'
services:
    paws-app:
        image: paws
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://paws-postgresql:5432/paws
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    paws-postgresql:
        extends:
            file: postgresql.yml
            service: paws-postgresql
