version: '2'
services:
    paws-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/paws/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=paws
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
